# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.0"
manifest_format = "2.0"
project_hash = "be162da0d558857edf606c3d7edbf805c39910c2"

[[deps.Fleckit]]
deps = ["Printf", "XML"]
path = "."
uuid = "5221e02f-f4f0-4a70-9dc4-802d9119ebc1"
version = "0.1.0"

[[deps.Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"
version = "1.11.0"

[[deps.OrderedCollections]]
git-tree-sha1 = "05868e21324cede2207c6f0f466b4bfef6d5e7ee"
uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
version = "1.8.1"

[[deps.Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"
version = "1.11.0"

[[deps.Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
version = "1.11.0"

[[deps.XML]]
deps = ["Mmap", "OrderedCollections"]
git-tree-sha1 = "6791d41872eb990faba2b72bd5e8c3d9035a188a"
uuid = "72c71f33-b9b6-44de-8c94-c961784809e2"
version = "0.3.8"
